#!/bin/bash
# _tools/keys/ssh/generate/repo-remote-connection/constants.sh


# Це файл, який допомагає правильно підключити згенерований ssh ключ до репозиторію. Містить набір підказок команд.
SSH_GIT_CONNECT_INSTRUCTION_FILE_NAME=".git-ssh-connection-instructions.md"

# Vars inside of templates to replace
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_REPO_ALIAS={{REPO_ALIAS}}
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_REPO_ABSOLUTE_PATH={{REPO_ABSOLUTE_PATH}}
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_SSH_KEYS_ABSOLUTE_PATH={{SSH_KEYS_ABSOLUTE_PATH}}
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_PRIVATE_SSH_KEY_ABSOLUTE_PATH={{PRIVATE_SSH_KEY_ABSOLUTE_PATH}}
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_PUBLIC_SSH_KEY_ABSOLUTE_PATH={{PUBLIC_SSH_KEY_ABSOLUTE_PATH}}
SSH_GIT_CONNECT_INSTRUCTION_TEMPLATES_VAR_INSTRUCTION_FILE_PATH_FROM_ROOT_REPO={{THIS_INSTRUCTION_FILE_PATH_FROM_ROOT_REPO}}